title: "DBML 2026"
description: >-
  5th International Workshop on Databases and Machine Learning (DBML 2026)
  in conjunction with CONFERENCE NAME.

url: "https://dataintelligencecrew.github.io"
baseurl: "/dbml26"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-seo-tag